### ISSUE TITLE
0.9.3 and Windows 10 Tech Preview: Over 9 Fleets! + no Repair/Construct tabs?

### ISSUE THREAD

**Issue by SoftwareGuy** [KanColleTool/KanColleTool#101]
![The bug](http://cache.coburnsdomain.com/ss-11102014/2014-10-11_21-48-27.png)
I have 2 ships being built and none docked. Weird bug with Windows 10, maybe something to do with QT5 not supporting the UI overhaul? How to replicate:

1) Obtain Windows 10 Tech Preview. Install inside VM, on a old box, etc
2) Install 0.9.3 of KCT
3) Do the funky stuff to login, etc.
4) Click on one of the fleet tabs. Cycle randomly through them; ie. 1, 3, 2, 4, 1...
5) Go to any page that features the fleet list (Docks, Equipment). Click the buttons to change the fleet you're looking at...
6) Go back to main screen with your ship girl that annouces hourly messages and look at KCT. You'll notice that huzzah, you've got another fleet for free. ~~Hax!~~

Sometimes the fleet pages get added while you're in fleet management section of the base. So yeah... must either be logic or a QT glitch.

**Comment by uppfinnarn** [comment]
Reopen if it reappears. The current tool UI will likely be scrapped for 1.0 either way in favor of a QML-based UI, which should get rid of any remainder of this bug.
