### ISSUE TITLE
Feature request: Allow user choose place to save screenshot (for Windows and Mac)

### ISSUE THREAD

**Issue by My2ndAngelic** [KanColleTool/KanColleTool#103]
As title, KCT has the best feature is allowing user to capture the screen.

But I would like to request a feature, that next release of KCT allows user to choose where to save the screenshot, also, please add this feature to Mac, since I have to use SnagIt to capture it every time.

Thanks

**Comment by uppfinnarn** [comment]
Finally shipped in 0.9.4.
