### ISSUE TITLE
Crash on launch (windows 8.1)

### ISSUE THREAD

**Issue by Green-Cat** [KanColleTool/KanColleTool#108]
I just downloaded the program from the website, and it crashes instantaneously on launch.
I've tried both the standalone and the installer.
I have flash player installed (it's working on firefox).
Is there any log or something I can consult somewhere?

**Comment by SoftwareGuy** [comment]
First, please check your machine for malware or any software that might be crashing KCT (ie. Malware Search Hooks). Secondly, run some tools like Wise Disk Cleaner and Wise Registry Cleaner (don't touch CCleaner, ever) to see if there is crap on your machine that could be interfering. Reboot after doing each clean.

Then try running KCT again. Please also attach a screenshot of the error window with the details pane open.

**Comment by uppfinnarn** [comment]
More importantly, can we get a crash log somehow? I know Windows is terrible at giving those, but I believe they should be there somewhere.

**Comment by uppfinnarn** [comment]
Closing since it's months old now, reopen if you can get a hold of that crash log.
