### ISSUE TITLE
KanColle API has changed so the tool needs a new release compatible with it.

### ISSUE THREAD

**Issue by EnderShadow** [KanColleTool/KanColleTool#110]

**Comment by SoftwareGuy** [comment]
Can you please tell us what's new? When did this API change happen?
At the moment I'm working on custom server software for KC, so I need to know what the new API structure is like.

**Comment by EnderShadow** [comment]
Sorry. I was mistaken. The tool had told me that the API changed so I thought I'd mention it, but the notice stopped appearing. Sorry for the false alarm.
