### ISSUE TITLE
KanColle Viewer only shows a white screen on OSX 10.10.2 Yosemite

### ISSUE THREAD

**Issue by EnderShadow** [KanColleTool/KanColleTool#111]
The API key works fine in the browser, but it doesn't appear to work in the application. I have the latest version of Adobe Flash Player installed.

**Comment by SoftwareGuy** [comment]
Maybe the security settings in OS X are blocking it? I dunno. I've only used 10.5.8 on a Mac Mini G4.

**Comment by EnderShadow** [comment]
If that is the case, where would the settings be? I didn't see anything unusual under the flash player settings.

**Comment by uppfinnarn** [comment]
There is no such thing on OSX. Security settings screwing with other programs is a Windows thing.

The only things I can think of are:

1. Adobe broke Flash Player. Again.
1. You're using Chrome, which is using its own embedded Flash Player, and doesn't use the system's.
1. Your Flash Player installation is broken - try reinstalling it as a last resort (not that it should matter).

**Comment by EnderShadow** [comment]
I don't think it's 1 because it works in firefox.
It's not 2 because I tested with firefox.
I don't think it's 3 either because it works in firefox.

**Comment by uppfinnarn** [comment]
Does anything show up in the Console when you start it?
Also, test with [QtWeb](http://qtweb.net), a small web browser using the same stack as the non-Mac Viewer.

(/Application/Utilities/Console.app)

**Comment by EnderShadow** [comment]
The KanColle Tool says it's waiting for me to start the viewer, but the viewer stays at a white screen. Is that what you mean by the console? QtWeb shows a grey screen when I try to run KanColle with it.

**Comment by uppfinnarn** [comment]
Safari? That's what the MacViewer is using for rendering.

**Comment by EnderShadow** [comment]
It shows up correctly there.

**Comment by uppfinnarn** [comment]
Then I have no idea, sorry :/
The MacViewer is just straight-up pulling in one of Safari's web views, so it should work if Safari does

**Comment by EnderShadow** [comment]
You know what. I was being stupid. I figured out the issue. I needed to put http:// in front of the api key for it to work.
