### ISSUE TITLE
Ro-500 name error.

### ISSUE THREAD

**Issue by My2ndAngelic** [KanColleTool/KanColleTool#114]
![2015-04-29_20-43-31](https://cloud.githubusercontent.com/assets/8387105/7408326/0b626428-ef1c-11e4-9e78-592fb8b9b255.png)
![2015-04-30_09-33-24](https://cloud.githubusercontent.com/assets/8387105/7408327/0b650ef8-ef1c-11e4-97e2-c921aa3ee18c.png)
![2015-04-30_09-35-00](https://cloud.githubusercontent.com/assets/8387105/7408342/34b35602-ef1c-11e4-9f46-b83a9303cfb8.png)

Some quick screenshot from KCT on Mac, English translation enabled. 
This problem happens with Ro-500 only.

**Comment by Yukariin** [comment]
Where is your error?

**Comment by My2ndAngelic** [comment]
Well, you can see the bottom line, that's when I left her in the repair bath.

**Comment by uppfinnarn** [comment]
This is… weird, I'm not even sure how that gibberish could even be possible o.O

Is it always the same too, or does it change between restarts?

**Comment by My2ndAngelic** [comment]
It always the same.
