### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by Siderg** [KanColleTool/KanColleTool#115]
Hello,
First of all thanks for great tool
And I really want to translate tool and some texts in game to Russian language
Can you share with me how can i do this?:)

**Comment by Yukariin** [comment]
> to Russian language

Могу тебя огорчить, дефолтный шрифт в клиенте абсолютно не поддерживает кирилицу и не читаем. Можешь посмотреть как в игре отображается `Верный`.
Если английский текст зачастую не влазит, то кирилица-то тем более.
Ты, конечно, можешь попробовать. Более-менее обновлённый перевод лежит в моей репе. Но что бы вьювер и тулза его подхватили тебе придётся заменить ссылку на файл перевода в сорцах и ребилднуть.

**Comment by Yukariin** [comment]
Алсо, насколько я знаю, @uppfinnarn работал над тулзой, для хака флеша на лету, которая позволила бы нам обновлять перевод, который захардкоден в клиенте, ну и починить шрифты для языков, отличных от Японского.
В каком оно сейчас состоянии - не знаю, но вряд ли готово хоть для какого-то использования...

**Comment by Siderg** [comment]
Ясно, спасибо за ответ, жаль что все так плохо. Просто побаловался немного с подменой кеша и для себя небольшой перевод  общего интерфейса сделал, а потом понял, что всякие там квесты, имена кораблей просто так не перевести. Потом наткнулся на эту тулзу с переведенными на английский именами и прочим.
![kancolle-150501-17160266](https://cloud.githubusercontent.com/assets/12198672/7431371/a84eb934-f026-11e4-9e82-66be9292315e.jpg)
Вот, что я пока сделал :)
Эх, было бы неплохо, если бы появились какие-то варианты для перевода текста.

**Comment by Yukariin** [comment]
Хммм, подмена кэша говоришь? Можно подробнее?
Не пробовал так же починить кирилицу в шрифте? Единственная проблема - это шрифт, если получится починить в нём кирилицу/заменить на другой, то останется только адаптировать англофикатор.

**Comment by Siderg** [comment]
Я силен в всем этом. Но мне однажды пришла мысль поковырять кеш браузера. Нашел я так .swf файлы игры, нашел в гугле декомпилер (JPEXS Free Flash Decompiler) который большинство этих файлов открывал + в нем легко заменить графические элементы на другие. Но так как я без понятия как подменить кеш в том же хроме, то взял программу HandyCache и пустил игру через него. Скачав все нужные .swf файлы, по открывал их и нашел нужные мне элементы, заменил с помощью JPEXS Free Flash Decompiler и сохранил, все. Игра к этим .swf файлам только обращается, не заменяет если они уже есть. Игра себе спокойно читает кеш с HandyCache и горя не знает, а у меня частично русский интерфейс. 
Насчет шрифтов, в кеше есть такой swf как font.swf там два шрифта, возможно это, то что нам нужно?
Вот он, я его закинул на ядиск https://yadi.sk/d/hbUgjeksgNV8z

**Comment by Yukariin** [comment]
Хотя, если подумать...
Сейчас у нас вьювер юзает вебкит и QNAM, который, по сути, работает как MITM-прокси.
Собственно в QNAM, у нас и реализуется перевод имён/квестов/эквипа. Туда же можно запихнуть и подмену (как из кеша, так и патчинг на лету) флешек.
Только вот я сомневаюсь, что это безопасно. Клиент постоянно обновляется же, поэтому нужно постоянно следить за изменениями и обновлять англо(ру)патчи для клиента. Да и вряд ли это понравится разрабам, которые, в свою очередь, могут запилить проверки для этого. Ну и пройтись банхаммером по нерадивимым игрокам со слишком длинными ручонками...

**Comment by Yukariin** [comment]
> возможно это, то что нам нужно?

Да, это оно. Дефолтный шрифт - AXIS.
Можешь посмотреть превью, например тут http://www.fonts.com/font/typeproject/axis-font-japanese/complete-family-pack
С кирилицей там плохо.

**Comment by Siderg** [comment]
Эх, в общем, яснопонятно. Ничего особо хорошего не выйдет, по крайней мере у меня.

**Comment by Yukariin** [comment]
Ну, если у тебя получилось заменить картинки, то и шрифт получится?
У меня правда через этот PEXS Free Flash Decompiler не экспортятся ttf из флешки...

**Comment by Siderg** [comment]
Экспортнуть шрифт можно, а вот обратно его закинуть - нет, ну или я не знаю как. С картинками там все просто, в JPEXS при нажатии на картинку есть функция замены, а тут нету, только экспортировать. Шрифт я вытянул, даже думал поправить кириллицу, да вот потом понял, что я без понятия как его назад в флешку закинуть потом:)

**Comment by Yukariin** [comment]
Ну, как вариант - попробовать декомпильнуть эту флешку и на основе структуры создать новую.
Она там вроде совсем простая, пара ttf, пара скриптов и всё.

**Comment by Siderg** [comment]
Собрать новую у меня не получается, при переводе флешки в .fla - проект пустой, совсем. Возможно я слишком дерево... Может у тебя это получится? Вот шрифты https://yadi.sk/d/LsbHCrHQgNc47 я еще не правил кириллицу, но могу хоть сейчас сесть, если в этом есть хоть какой-то смысл.

**Comment by Yukariin** [comment]
Экспорт в FLA и XML у меня тоже пустой. Можно попробовать платные декомпиляторы-эдиторы.
У меня пока не особо много времени на это, может ближе к ночи освобожусь и тоже попробую.

**Comment by Siderg** [comment]
Дак этож не горит:) Конечно, как будет время и желание, хоть завтра, хоть через неделю. Было бы классно с этим разобраться. А я попытаюсь помочь чем смогу, т.ч пойду таки поправлю кириллицу, может будет полезно.

**Comment by uppfinnarn** [comment]
![img_0151](https://cloud.githubusercontent.com/assets/428026/7434148/79f8c50e-f038-11e4-882b-9260597c620d.jpg)

**Comment by Yukariin** [comment]
@uppfinnarn :3

**Comment by uppfinnarn** [comment]
@Yukariin 
![screen shot 2015-01-15 at 07 48 57](https://cloud.githubusercontent.com/assets/428026/7434166/d2fa53fc-f038-11e4-9f54-ce24e7edaf2a.jpg)

**Comment by Yukariin** [comment]
@uppfinnarn Good nigh!
![dcb5c9bf2f36c7fbd5c8b596e62595f6](https://cloud.githubusercontent.com/assets/6450725/7434200/9bedcbd8-f041-11e4-9177-e72fdc66afd4.png)

**Comment by SoftwareGuy** [comment]
Unless we have a russian translator that knows both Japanese and Russian and can make a translation proxy then I guess that would work. At the moment I think translations are done via a Commie Fansubs proxy hosted by RHExcelion (could be wrong).

**Comment by Yukariin** [comment]
> At the moment I think translations are done via a Commie Fansubs proxy hosted by RHExcelion

This translation is outdated and will not be updated because translator was gone.

**Comment by Yukariin** [comment]
@Siderg В общем у меня получилось восстановить структуру проекта - там ровно 1 дефолтный кадр, 2 шрифта и 2 дефолтных класса к ним. http://rghost.ru/6HscZ4spV
Получилось пофиксить кирилицу?

**Comment by Siderg** [comment]
Да, спасибо за труды. Мне удалось поменять кириллицу и игра ее вроде как приняла. Ну, долна была. Просто у меня нету верного чтобы проверить, а другого именно русского текста в игре я не знаю. Но, я проверял другим вариантом, исказил некоторые буквы английские в шрифте по тому же принципу, что и кириллицу. И после очистки всех кешей, особенно RAM-кеша в handycache и выставив там же, чтобы файл фонт брался только из кеша, я увидел изменения в игре. 
Так, что все должно работать, вот последний свф файл который у меня сейчас в игре с измененной кириллицей - https://yadi.sk/d/hbUgjeksgNV8z
Таким образом, стоит вопрос только в русификации самих текстов, шрифт в моем случае уже не проблема. Если бы для этого еще был более удобный вариант изменения шрифта, а то чтобы запустить русский в игре придется долго плясать с бубном)

**Comment by Yukariin** [comment]
Круто, чем шрифт правил? Правил уже существующие в шрифте символы или залил из другого шрифта? Можешь отдельно пофикшенный шрифт выложить?

> Если бы для этого еще был более удобный вариант изменения шрифта, а то чтобы запустить русский в игре придется долго плясать с бубном)

Для начала скажи, что за ОСь у тебя? В линуксе ребилднуть значительно проще, чем в винде.
А так тебе нужно только одну ссылку поменять в сорцах.

**Comment by Siderg** [comment]
FontCreator правил, залил с Ариала, не знал какой выбрать, выбрал самый обычный)

А вот сам шрифт - https://yadi.sk/d/unoXfdyPgPVbE

Сейчас сижу на Вин 8.1

**Comment by Yukariin** [comment]
Хотя стоп, если твоя прокся может подменять флешки, тогда просто подмени файл перевода.
https://github.com/Yukariin/Yukariin.github.io вот тут у меня обновлённый английский перевод, который будет юзаться в новых версиях вьювера.
Скачай, подредактирую и похакай его проксёй, как и флешку с шрифтами.

**Comment by uppfinnarn** [comment]
I'm just going to close and unsubscribe from this now. Feel free to continue.

**Comment by Siderg** [comment]
не получится, флешки то идут через кеш, поэтому я их могу подменить. А эти файлы по всей видимости через кеш не проходят, т.ч. подменить у меня не выйдет никак.

**Comment by Yukariin** [comment]
Хендикеш - это ведь по сути обычная прокси? Так вот перевод точно такой же HTTP-запрос, как и выкачивание флешки у DMM.

**Comment by Siderg** [comment]
Вот собственно что подгружает хендикеш от старта вьювера до загрузки в порт. Позже особо запросы не меняются. Я просто не вижу таких файлов в кеше, может я чего не понимаю.
http://s7.hostingkartinok.com/uploads/images/2015/05/48f1b86ee3f7c298ef13aea2ae118e92.png

**Comment by Yukariin** [comment]
А да, точно, там же отдельный QNAM для запроса переводов, он настройки прокси из тулзы не читает.

**Comment by Yukariin** [comment]
Тогда придётся редактировать ссылку в сорцах и ребилдить.

**Comment by Siderg** [comment]
Пичаль, а гайда как это сделать нигде нету? А то я такого никогда не делал.

**Comment by Yukariin** [comment]
В винде с этим геморно всё -___-
Дай мне ссылку на файл, который ты хочешь обновлять, и я попробую тебе билднуть вин-версию.

**Comment by Siderg** [comment]
а ну, тогда пока ничего не нужно. Это ведь перевод нужно иметь, чтобы что-то обновлять :) Зачем лишний раз воду гонять. Тогда такой вопрос, где взять тексты? Они там все по той ссылке с обновленным англ переводом? И его просто можно брать и переводить? Собственно это и был основной вопрос темы, просто все как-то ушло немного в другую сторону. И тогда, как будет что показать - можно будет и ребилдить) Я просто позже обращусь насчет ребилда сюда или куда-то, куда будет удобней. Вряд ли это будет скоро.

**Comment by Yukariin** [comment]
Ну, основная проблема, как ты мог заметить, это шрифты. Который фиксятся только подменой флешки с шрифтами на свою.
Для этого нужно будет делать отдельную настройку и хак в QNAM, который будет в зависимости от настройки качать оригинальный/починенный шрифт.
Надо будет у автора узнать ещё, не против ли таких хаков он...

**Comment by Siderg** [comment]
Ок, если не сложно узнай у него. Я тогда с текстами пока подожду, займусь правкой картинок и ожиданием не забанят ли меня за это, заодно проверю как эта тема работает с обновлениями клиента, а то картинки я не успел подменить до весеннего ивента, а клиент на время его точно обновлялся. После него будет видно, рабочий ли мой вариант или нет.
Все равно мой способ перевода интерфейсных кнопок не имеет отношения к тулзе.

**Comment by Yukariin** [comment]
По хорошему бы нам нужна тулза, которая бы это автоматом делала, а не руками каждый раз.
Ну и у меня вот сейчас дошли руки до FontForge и я начинаю фиксить кирилицу, которая уже есть в шрифте.

**Comment by Siderg** [comment]
Тулза это конечно круто, но думаю сложновато из-за swf`ок, хотя я не шарю. Мой предел это какие-нибудь несложные задачки на ruby писать, да код читать :D

**Comment by Yukariin** [comment]
В общем Юкарин сделала временный хак, чисто для проверки, работает:
![27](https://cloud.githubusercontent.com/assets/6450725/7453875/73c5ed2a-f276-11e4-8c9c-376c6512fc71.png)
Но некоторые буквы латиницы выглядят мягко говоря ниочень. Буду пилить символы, которые уже есть в шрифте...

**Comment by Siderg** [comment]
Круто, а этот хак получается идет как дополнение к вьюверу или это что-то отдельное? Мне вообще интересно, а можно эту подмену японского текста на тот же английский сделать более универсальной? Имеется введу отвязать от тулзы и вьювера, а запускать отдельно, чтобы оно работало не только в них, а и в том же браузере. Ведь, например, та же замена кеш файлов, которую я юзаю для картинок, универсальна в этом плане. Просто интересно узнать)

**Comment by Yukariin** [comment]
Нет, просто подмена (по сути то, что у тебя делает прокси) оригинального файла на кастомный в ответе. Но оно кривое пока и вообще никак не настраиваемое.
Часть текстов передаёт клиенту апи, собственно их не так уж сложно перевести при помощи MITM-прокси, в качестве которой у нас работает QNAM.
Так что это можно будет сделать при помощи другой прокси, которую в браузере можно будет включить.
Тоже самое с флешками, я сейчас курю формат swf и либу FFDEC. Попробую сделать патчер...

**Comment by Yukariin** [comment]
На самом деле в канколле всё сделано через жопу.
Возможностей перевода практически нет. Передача текстов с апи - это вообще шедевр. Внутриигровые тексты наглухо забиты в клиент.
В качестве сравнения могу привести SGO (Sword Girls Online) очень похожая как по жанру так и в целом по устройству и механике браузерку. Так вот, там большинство текстов раскидано по обычным XML, которые в зависимости от локали подтягиваются. С сервера никаких текстов в ответах нет, просто потому что они там нахрен не нужны. Но часть текстов всё таки в клиент забита.

**Comment by Siderg** [comment]
С текстов в апи я тоже немного прифигел, когда увидел.
А так, через пень-колоду вполне можно сделать вменяемый перевод xD Хоть и геморрно это. 
Хотелось бы помочь как-то с программной частью, да я слишком дерево в этом.
Вообще, было бы реально классно иметь отдельный универсальный инструмент с переводом, но пока это мечты-мечты. 
Если я чем-то могу помочь - скажи, я постараюсь это сделать.

**Comment by Yukariin** [comment]
В FontForge, оказывается, есть такая штука, как автоматическое выставление ширины символа.
Починенный шрифт с кирилицей теперь тут https://github.com/Yukariin/Yukariin.github.io/tree/master/font
Нужно будет потом ребилднуть флешку с новым шрифтом...

**Comment by Siderg** [comment]
мм, поставил в флешку новый шрифт, вот - https://yadi.sk/d/fYGd0h1CgWbsu

**Comment by Yukariin** [comment]
@Siderg в общем пилится потихоньку парсер: 
![2015-06-20-192414_710x240_scrot](https://cloud.githubusercontent.com/assets/6450725/8268127/f676b1ca-1781-11e5-8646-20ba176cbce6.png)
По большей части копипащу из ffdec_lib с небольшими адаптациями под кресты.

**Comment by Rhextian** [comment]
are you guys still looking for english translator? if so, i wanna help out

**Comment by Yukariin** [comment]
@Rhextian well, currently we have our own translation, that placed in my repo https://github.com/Yukariin/Yukariin.github.io
And upstream version of KCT already support it. Just clone and build Viewer/Tool from upstream.
If you interested to contribute - you can fork my repo, make changes and then make pull request.

**Comment by Rhextian** [comment]
i tried building the tool, but cmake gives me this error, am i missing something? i already installed Qt5 as well
![d7ce8a100e](https://cloud.githubusercontent.com/assets/12529719/8354589/d769517c-1b7b-11e5-8c39-afa5b888d810.png)

**Comment by Yukariin** [comment]
@Rhextian easiest way is install latest version of Qt5 from official site, clone repo with submodules, launch Qt Creator and open CMakeLists.txt from root of cloned repo.

**Comment by Rhextian** [comment]
i tried building it from qt5 like u said, but i cant seem to run both the tool and the viewer, it says Qt5Widgets.dll is missing or something

**Comment by Yukariin** [comment]
@Rhextian yep, you need copy Qt .dll's to .exe folder. See latest Standalone version from here https://kancolletool.github.io/downloads/

**Comment by Rhextian** [comment]
oh btw, w/c version of qt5 i should use? i got 5.4.1 atm

**Comment by Yukariin** [comment]
> w/c version of qt5 i should use? i got 5.4.1 atm

We don't use any version-specific Qt features. So you can use any 5.* version.

But I'll recommend you to use latest version because they may contains some bug-fixes and/or improvement.

**Comment by Rhextian** [comment]
oh ok, it works now but it doesnt seem to load the translation even though the translation box is ticked

**Comment by Yukariin** [comment]
@Rhextian strange... You have all quests on japanese?
Works fine for me:
![kctviewer 2015-06-27 20 50 57](https://cloud.githubusercontent.com/assets/6450725/8393211/7371212e-1d0e-11e5-85dd-a6fef8f16819.png)

**Comment by Siderg** [comment]
Увидел шевеления в тему и вспомнил, что хотел поделится не самый приятным опытом. В общем, неделю назад словил я бан в игре, скорей всего за модификацию кэша, хотя японцы упорно молчат о том, что же я не так сделал, но так как других причин не было, ну кроме того что я не японец, то скорей всего так оно и есть.

**Comment by Rhextian** [comment]
yeh, everything is on japanese and every time i run the program, it gives me this error
![cc37a3cd87](https://cloud.githubusercontent.com/assets/12529719/8395039/0177ec76-1d89-11e5-92eb-9d77c3a041b5.png)

**Comment by kevin01523** [comment]
the english translation kinda stopped i mean http://api.comeonandsl.am/translation/%1/ returns null

**Comment by Yukariin** [comment]
> also my .exe is requesting dll with the d instead of the plain dll (eg. Qt5Guid.dll instead of Qt5Gui.dll)

`d` - it's debug version of libraries. You're .exe require debug lib's because you build Debug target on Qt Creator. Select Release and rebuild.

**Comment by kevin01523** [comment]
use cmd
then cd to  C:\Qt\Qt5.*.*\5.*\msvc2013\bin depends on what version you are using
then  paste the command bellow it will copy the needed dll's

windeployqt --no-compiler-runtime --no-translations --no-svg  %KCT dir%\KCTViewer.exe

windeployqt --no-compiler-runtime --no-translations --no-svg  %KCT dir%\KanColleTool.exe

**Comment by Yukariin** [comment]
@Siderg так тебя забанили или нет за модификацию клиента?
Потому как меня за простую подмену `font.swf` https://github.com/KanColleTool/KanColleTool/issues/115#issuecomment-98699490 до сих пор не прибили.

**Comment by Siderg** [comment]
Если честно, я хз за, что меня забанили. Они ничего не написали. А я ничего, кроме как этой подмены для перевода, не использовал. Возможно это был просто какой-то шальной бан, а может я кэш где-то не обновил после очередного обновления игры из-за чего меня накрыли. Если бы kadokawa мне хоть что-то ответили... Я им писал 2 раза, но нифига... Зато когда первый раз написал к DMM, они мне в тот же день ответили и сказали мол, это не к нам пишите кадокаве и описали как это сделать. А эти уже ни слухом, ни духом, забанили и молчат.

**Comment by Yukariin** [comment]
@Siderg скрипты не трогал в флешках?

**Comment by Siderg** [comment]
@Yukariin нет конечно, я там все равно ничего особо разобрать не смог, да и зачем.
