### ISSUE TITLE
KanColleTool 0.9.4 will not allow user to "Get API Link" (Win32 build only)

### ISSUE THREAD

**Issue by SoftwareGuy** [KanColleTool/KanColleTool#124]
**Problem:**
Using the "Get API Link" function results in a white page.

*wrong, my bad, this was the original issue*
~~KanColleTool may crash when one goes to use the option "Get API Link" and clicks either "English" or "Japanese" on the "Welcome to DMM" popup. This is caused by an oversight of not having the SSL libraries included with 0.9.4 as the "Get API Link" contains a login page which then submits to a HTTPS location. The error will be 0xC000005 (Access violation/Failed to initialize) from Windows referencing ssleay32.dll.~~

**Serverity:**
Minor. Only affects people trying to get API token through KCT.

~~Low. Will not break main game. Happened once, but can't get it to trigger again after it crashed the first time. :unamused: May only happen on "virgin" Windows machines, ones that do not have OpenSSL installed.~~

**Who's to blame:**
Myself, I was the one who didn't include the SSL binaries. I can quickly put together a repack with the DLLs required in both ZIP and Installer form.

**End-user solution:**
Download/install 0.9.3, then do a over-the-top copy/install of 0.9.4. Click the menu and then "Get API Link". DMM Login should appear.

Alternative solution:
The end user needs to go to [the OpenSSL website](https://www.openssl.org/related/binaries.html) and download the latest DLLs for windows from one of the mirrors. I personally downloaded the latest version (1.0.2d at the time of writing) from [this mirror](http://indy.fulgan.com/SSL/) called openssl-1.0.2d-i386-win32.zip and unpacked the ZIP to the KCT directory. **DO NOT USE THE x86_64 VERSIONS.** Then launch KCT again.

@uppfinnarn, could you please put a reference to this issue on the site until I resolve the goof up? Thanks.

**Comment by Yukariin** [comment]
> The end user needs to go to the OpenSSL website and download the latest DLLs for windows from one of the mirrors. I personally downloaded the latest version (1.0.2d at the time of writing) from this mirror called openssl-1.0.2d-i386-win32.zip and unpacked the ZIP to the KCT directory.

Wat?
Previous version of KCT contains OpenSSL libs in standalone and installer and works fine.

**Comment by SoftwareGuy** [comment]
Yes, one can install 0.9.3 and then update to 0.9.4 but this oversight is my error because I didn't realize the "Get API Link" function uses a SSL connection. 

Actually you know what? The reason I got that crash was bloody Windows was loading the SSL files from a PHP directory that I have on my development stack. If you use "Get API Link" and you don't have the DLLs, you get a white page. If you have the DLLs, you don't get a white page.

Fixing issue to reflect this.

**Comment by SoftwareGuy** [comment]
@uppfinnarn Can you change the download packages to [this one for the extract and run package](http://cache.coburnsdomain.com/kct/KCT_094_r6_win32-xptarget_sslfixed.zip) and [this one for the installer](http://cache.coburnsdomain.com/kct/KCT_094_r6_installer.zip). Both are updated with the SSL libs, which would then make this issue obsolete and everyone happy.

**Comment by uppfinnarn** [comment]
Gah, this was buried under a mountain of unimportant emails. You may need to build it as 0.9.5 and push it as an update, because otherwise everyone who installed it already will have a broken install.

**Comment by SoftwareGuy** [comment]
@uppfinnarn Sure thing. Should I fork this repo, make my changes (up the version number) and then submit a pull request so you can sync and I'll provide packages?

**Comment by uppfinnarn** [comment]
That works

**Comment by SoftwareGuy** [comment]
![image](https://cloud.githubusercontent.com/assets/1762115/9159676/bdf97d20-3f70-11e5-8e83-769c6efb05b3.png)
**Version 0.9.5: SoftwareGuy broke something but then DMM broke it even more Edition**

Build done, uploading now.

**Comment by SoftwareGuy** [comment]
@uppfinnarn Here you go:
Installer: http://cache.coburnsdomain.com/kct/KCT-095-Win32-Setup.zip
Installer: http://cache.coburnsdomain.com/kct/KCT-095-Win32.zip

**Changelog**
- Tool uses up-to-date submodule code.
- Viewer uses latest code up to kct-viewer commit ddf5f2d92d2eacf591a1b6e5875dad9ed4ef9b82. Latest commit causes compiler errors, something about OneShot taking only 1 parameter, not 2.
- This may not even be 0.9.5, but it's a stop-gap release to fix my goofs on 0.9.4.

*Unable to test the build if it's going to work or not in-game because I get errorcat likely due to maintenance window.*

**Comment by SoftwareGuy** [comment]
Actually... fudge. DMM did a hard one on us.

![image](https://cloud.githubusercontent.com/assets/1762115/9160239/ff457adc-3f79-11e5-86aa-7f204ccf029a.png)

Thanks a lot, DMM.

**Comment by Yukariin** [comment]
Huh? Viewer and Tool works fine for me.

**Comment by Rhextian** [comment]
also works fine on my side, well that error showed up once when it was maintenance though

**Comment by uppfinnarn** [comment]
@SoftwareGuy I do not appreciate sneaky changes to the README with no discussion around the change or its wording.

**Comment by SoftwareGuy** [comment]
@uppfinnarn no worries, I'll revert it.

**Comment by uppfinnarn** [comment]
0.9.5 is out!
