### ISSUE TITLE
API Link Expires as of October 9, 2015 Patch

### ISSUE THREAD

**Issue by Rhextian** [KanColleTool/KanColleTool#131]
**Problem:**
API Link now expires when you restart KCTV, Refresh (F5) the game (catbomb or not) or when you idle for 20-30mins
more info http://kancolle.wikia.com/wiki/User_blog:Dragonjet/API_Links:_October_2015

**Serverity:**
Minor? Every time you get a catbomb, you will be forced to Refresh your API Link

**Who's to blame:**
DMM, they probably implement this feature to avoid people from using bots.

**End-user solution:**
Refresh your API Link every time you get a catbomb from "Get API Link" in the Game Menu or KC3改

**Proposed solution**: @uppfinnarn 
Instead of directly loading from the entered API Link, why not load it from DMM Kancolle  http://www.dmm.com/netgame/social/-/gadgets/=/app_id=854854/ first then KCTV automatically extract your API Link then Load it from there every time you start/refresh the game.

**Comment by SoftwareGuy** [comment]
As soon as a patch(set) is released, I'll get compiling a new build.

That's kinda a pain in the bum though, because if you get a catbomb (either game derped, or your internet reset the connection - happens here in AU on 3G) you'll have to log in all over again.

I have been tinkering with the welcome page idea @uppfinnarn proposed but honestly I don't have the energy right now to look at the code and make appropriate modifications, then do a pull request etc. Given I've kinda pushed 2D shipwaifus aside for 3D shipwaifus in WoWS... I'll compile regardless.

**Comment by kevin01523** [comment]
oh so were on same server then on wows asia.idling can vary ive been idle for about 8 hours and did not get catbomb but once i refreshed expired api link.the server invalidates the api link if the api token is authenticated again

**Comment by SoftwareGuy** [comment]
The question I have is this...

Could we get around this timeout if we do a polling in the background, to the port status API? Or would that botch things up if you're in battle and it's currently showing what you fleet is doing and KCT asks the server for an updated set of values (ie. fleet vitals, what's being constructed, etc).

By polling, we'd be keeping the "i'm a genuine player" flag active. I know from stuff I've read on IRC is that some non-japanese players will keep KanColle minimized and muted, so when they want a quick break they send a fleet on expedition. I guess this clogs up the server and can waste bandwidth...

**Comment by Rhextian** [comment]
i think we wont have to worry about the idle problem anymore

![1fc88b3096](https://cloud.githubusercontent.com/assets/12529719/10416884/a33406dc-705c-11e5-8e90-a5621e0ec114.png)

only thing left now is the restart KCTV / refresh (f5) problem

**Comment by uppfinnarn** [comment]
Deja vu.
Remember last year when they pulled something like this, then the servers died from an onslaught of people reloading the whole damn game?

From what we know of the KCStaff and DMM, it's likely executive meddling from DMM's part, but at least KCStaff aren't dumb enough to bring down their entire service over this.

Also @SoftwareGuy, please stop going offtopic in every single thread you participate in. Thank you.
