### ISSUE TITLE
Luck modernization is blocked

### ISSUE THREAD

**Issue by strongestFairy** [KanColleTool/KanColleTool#133]
Version: 9.6
OS: Win7x64
Watch the pic below. A modernization button is unavailable and Luck counter is not updated.
![A try](http://i.imgur.com/RHxiHRY.png)

Successfully upgraded luck directly at DMM site.

**Comment by Yukariin** [comment]
AFAIK this is because Maruyu name was translated and original Japanese name used in client code (yep).
Try to disable English translation.

**Comment by strongestFairy** [comment]
Disabling English did the magic. Thank you （｀・ω・´）b
