### ISSUE TITLE
error in "make install" command for serial communication in ubuntu

### ISSUE THREAD

**Issue by parijohn** [KanColleTool/KanColleTool#134]
hi, I am trying to run serial communication program in ubuntu 14.04.3, after make command , i tried to execute make install command but it gives following error:
pari@my-project:~/work/serial$ make install
cd build && make install
make[1]: Entering directory `/home/pari/work/serial/build'
make[1]: *** No rule to make target `install'.  Stop.
make[1]: Leaving directory `/home/pari/work/serial/build'
make: *** [install] Error 2
moreover, i also tried this with root login but it also gave the same error.
your help will be highly appreciated
Regards

**Comment by uppfinnarn** [comment]
This has nothing to do with KCT, did you post in the wrong project?
