### ISSUE TITLE
Cannot run on Windows XP

### ISSUE THREAD

**Issue by kevin01523** [KanColleTool/KanColleTool#97]
well it seems both the viewer and the tool is not recognized as a proper win32 application or valid an exe 

here is  screenshot

http://i.imgur.com/nzWDXbM.jpg
![10534484_778283928904752_865293190_n](https://cloud.githubusercontent.com/assets/8380242/3948133/d992fb7e-269e-11e4-8c96-cad4d6ccec99.jpg)

**Comment by uppfinnarn** [comment]
Should be merged into the latest release.
